/**
 * Report Generator Service (Feature 6)
 * Processes collections of threats into standard formats (CSV, JSON, Markdown).
 */

export interface ReportRecord {
  id: number;
  type: string;
  target: string;
  riskScore: number;
  riskLevel: string;
  findings: string[];
  createdAt: string;
}

/**
 * Converts scan history records into a standard CSV string.
 */
export function generateCSVReport(records: ReportRecord[]): string {
  const headers = ["Scan ID", "Vector Type", "Target Asset", "Risk Score", "Risk Level", "Timestamp", "Findings Count"];
  const rows = records.map(r => [
    r.id,
    r.type.toUpperCase(),
    `"${r.target.replace(/"/g, '""')}"`,
    r.riskScore,
    r.riskLevel.toUpperCase(),
    r.createdAt,
    r.findings.length
  ]);

  return [headers.join(","), ...rows.map(row => row.join(","))].join("\n");
}

/**
 * Converts scan history records into a clean JSON string.
 */
export function generateJSONReport(records: ReportRecord[]): string {
  return JSON.stringify(records, null, 2);
}

/**
 * Formats a threat scan analysis into a beautifully structured Markdown summary report.
 */
export function generateMarkdownReport(record: ReportRecord, explanation?: string, recommendations?: string[]): string {
  return `
# 🛡️ PhishGuard AI Threat Scan Report
**Scan Reference ID:** #${record.id}  
**Timestamp:** ${record.createdAt}

---

## 📊 Executive Analysis
* **Vector Type:** ${record.type.toUpperCase()}
* **Analyzed Target:** \`${record.target}\`
* **Risk Score:** **${record.riskScore}/100**
* **Classification:** ${record.riskLevel.replace("_", " ").toUpperCase()}

---

## 🔍 Core Security Findings
${record.findings.map(f => `* ${f}`).join("\n")}

---

## 🤖 AI Threat Explanation
${explanation || "No advanced AI explanation requested for this scan session."}

---

## ⚡ Incident Response Recommendations
${recommendations && recommendations.length > 0 
  ? recommendations.map(rec => `1. **${rec}**`).join("\n")
  : "1. No immediate recommendations supplied."}

---
*Generated by PhishGuard AI Phishing Detection Platform. Confidential and Protected.*
`;
}
